# Generated by Django 4.0.1 on 2022-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer_app', '0002_alter_player_options_remove_game_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_in_game',
            field=models.BooleanField(default=False),
        ),
    ]
