# Generated by Django 4.0.1 on 2022-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer_app', '0003_player_is_in_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
