# Generated by Django 4.0.1 on 2022-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer_app', '0004_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='target_action',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='target_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
